apiVersion: v1
kind: Service
metadata:
  name: postgres-np
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
