apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deployment
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: shiveshk/catalog.api:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: IdentityServiceUrl
              valueFrom:
                configMapKeyRef:
                  name: catalog-api-config
                  key: IdentityServiceUrl
            - name: ConnectionStrings__Database
              valueFrom:
                secretKeyRef:
                  name: catalog-api-secret
                  key: connString

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-np
spec:
  type: NodePort
  selector:
    app: catalog-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31600

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api-clusterip
spec:
  type: ClusterIP
  selector:
    app: catalog-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
