apiVersion: v1
kind: Service
metadata:
  name: mssql-np
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30003
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mssql-clusterip
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
