apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: postgresSecretPw

---
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
stringData:
  password: mssqlSecretPw

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  username: rabbitUn
  password: rabbitSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
type: Opaque
stringData:
  connString: "Server=postgres-clusterip;Port=5432;Database=postgres;User Id=postgres;Password=postgresSecretPw;Include Error Detail=true"

---
apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
type: Opaque
stringData:
  connString: "Server=postgres-clusterip;Port=5432;Database=postgres;User Id=postgres;Password=postgresSecretPw;Include Error Detail=true"
