version: '3.4'

services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  identitydb:
    image: postgres
  orderdb:
    image: mcr.microsoft.com/mssql/server
  distributedcache:
    image: redis
  messagebroker:
    image: rabbitmq:management
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: Services/Discount/Discount.Grpc
      dockerfile: Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: ApiGateways/YarpApiGateway
      dockerfile: Dockerfile  

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: IdentityService
      dockerfile: Dockerfile

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: WebApps/Shopping.Web
      dockerfile: Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  postgres_identity:








