version: '3.4'

services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  identitydb:
    image: postgres
  orderdb:
    image: mcr.microsoft.com/mssql/server
  distributedcache:
    image: redis
  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: Services/Discount/Discount.Grpc
      dockerfile: Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: ApiGateways/YarpApiGateway
      dockerfile: Dockerfile  

  identity:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: IdentityService
      dockerfile: Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  postgres_identity:







